version: "3"
services: 
  app:
    volumes:
      - app_node_modules:/app/node_modules
      - dist:/app/dist
      - ../app:/app
    command: sleep infinity
    ports:
      - 8080:8080
  api:
    volumes: 
    - api_node_modules:/api/node_modules
    - ../api:/api
    command: sleep infinity
    ports:
      - 8443:8443
  
volumes:
  app_node_modules: {}
  api_node_modules: {}
  dist: {}
