version: "3"
services: 
  app:
    volumes:
      - app_node_modules:/app/node_modules
      - dist:/app/dist
      - ../app:/app
    command: sleep infinity
    ports:
      - 8080:8080
volumes:
  app_node_modules: {}
  dist: {}
